# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(ranger)
    library(recipes)
    library(workflows)
}
b <- board_folder(path = "C:/Users/LENOVO/Documents/Projets_ML/CardioVasculairePredict/version_models_R/VetiverPinsVersion1")
v <- vetiver_pin_read(b, "RandomForestVersion1")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
